spring:
  application:
    name: library-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080
server:
  port: 8081

book-service:
  base-url: http://localhost:8082
  credentials:
    username: library-service-account
    password: super-secret-service-pass