spring:
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: a92285001@smtp-brevo.com
    password: xsmtpsib-2e2f110ed0d459765864a299527b85877545b694587bb23b3e848c238940ca8f-MRkik0gRn0MiSte2
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
  security:
    user:
      name: library-service-account
      password: super-secret-service-pass
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdetails
    username: postgres
    password: mahshoq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8082

app:
  notification:
    super-admin-email: serverspring386@gmail.com
    from-email: mahshoq.work@gmail.com