spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 6f76ccc06be5f9
    password: ce9e0527f873c4
    properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
  security:
    user:
      name: library-service-account
      password: super-secret-service-pass
  application:
    name: book-service
  datasource:
    url: jdbc:postgresql://localhost:5432/userdetails
    username: postgres
    password: mahshoq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8082

app:
  notification:
    super-admin-email: superadmin@gamil.com
